### ISSUE TITLE
Problem in Upgrade to a Pay-as-you-go

### ISSUE THREAD

**Issue by namlhn** [IBM-Bluemix-Docs/billing-usage#12]
I want to try Blockchain Platform, and I had upgraded my IBM account, but I got an error for payment: "Error: Could not place order. Problem authorizing the credit card. We are unable to process your request: Transaction Rejected. Please contact Cloud Trust Enablement at verify@us.ibm.com for further information." , I payment with Vietnam's Credit Card.

My IBM Accout: namlh@dgk.vn 

I'm very appreciate for your help

**Comment by cjcarpen** [comment]
Hi @namlhn , thanks for reaching out! Was the team over at verify@us.ibm.com able to help sort out the issue with your card?

**Comment by cjcarpen** [comment]
I'm closing this issue because it doesn't seem like any doc updates are needed, but please reach out to verify@us.ibm.com if you continue to experience issues or open a support case here: https://cloud.ibm.com/unifiedsupport
