### ISSUE TITLE
The wording on the "Estimating your costs" section of the specified page is incorrect

### ISSUE THREAD

**Issue by chris-ratcliffe** [IBM-Bluemix-Docs/billing-usage#4]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
The wording on the "Estimating your costs" page is incorrect.  It currently says "You can estimate the costs of classic infrastructure offerings if you have a Pay-As-You-Go or Subscription account. To upgrade your Lite account, see Upgrading your account." however, the estimation tool is available for the entire cloud catalog (or at least, for more than just classic infrastructure) and it also doesn't require any type of specific account, in fact, its available to be used without even authenticating.  

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-cost#cost

3. Do you have a suggestion about how to resolve the issue?
Simply change it to something like: "You can estimate the costs of any offering in the IBM Cloud catalog, even without signing up for an IBM Cloud account."

**Comment by cjcarpen** [comment]
@chris-ratcliffe Thanks for submitting this suggestion! We removed the incorrect statement and updated the rest of the instructions for the current cost estimator. Check it out here: https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-cost#cost
